NYU: 
  redirects: 
    - ""
    - NYU
NYUAD: 
  redirects:
    - NYUAD
NYUSH: 
  redirects:
    - NYUSH
NS:
  redirects:
    - NS
CU:
  redirects:
    - CU
NYSID:
  redirects:
    - NYSID
HSL:
  redirects:
    - HSL
NYHS:
  redirects:
    - NYHS
BHS:
  redirects:
    - BHS